# Generated by Django 5.0.1 on 2024-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('done', models.BooleanField(default=False)),
                ('tasks', models.ManyToManyField(to='main.task')),
            ],
        ),
    ]
