# Generated by Django 5.0.1 on 2024-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
                ('projects', models.ManyToManyField(to='main.project')),
                ('tasks', models.ManyToManyField(to='main.task')),
            ],
        ),
    ]
